function Jst_lhand = auto_Jst_lhand(l2,lt,phi,q2,wt)
%auto_Jst_lhand
%    Jst_lhand = auto_Jst_lhand(L2,LT,PHI,Q2,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:18

t2 = cos(phi);
t3 = cos(q2);
t4 = sin(phi);
t5 = sin(q2);
t8 = lt./2.0;
t9 = wt./2.0;
t6 = l2.*t3;
t7 = l2.*t5;
t10 = t6+t8;
t11 = t7+t9;
Jst_lhand = reshape([1.0,0.0,0.0,1.0,-t2.*t10+t4.*t11,-t2.*t11-t4.*t10,0.0,0.0,-t2.*t6+t4.*t7,-t2.*t7-t4.*t6,0.0,0.0,0.0,0.0],[2,7]);
end
