function h = auto_h(q1,q2,q3,q4,qd1,qd2,qd3,qd4)
%AUTO_H
%    H = AUTO_H(Q1,Q2,Q3,Q4,QD1,QD2,QD3,QD4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:19

h = [q1-qd1;q2-qd2;q3-qd3;q4-qd4];
end
