function p_rhand = auto_prhand(l1,lt,phi,q1,wt,x,y)
%AUTO_PRHAND
%    P_RHAND = AUTO_PRHAND(L1,LT,PHI,Q1,WT,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:15

t2 = cos(phi);
t3 = cos(q1);
t4 = sin(phi);
t5 = sin(q1);
t8 = lt./2.0;
t9 = wt./2.0;
t6 = l1.*t3;
t7 = l1.*t5;
t11 = t6+t8;
p_rhand = [x-t4.*t11-t2.*(t7-t9);y+t2.*t11-t4.*(t7-t9)];
end
