function Jstdot_lfoot = auto_Jstdot_lfoot(l4,lt,phi,phidot,q4,q4dot,wt)
%auto_Jstdot_lfoot
%    Jstdot_lfoot = auto_Jstdot_lfoot(L4,LT,PHI,PHIDOT,Q4,Q4DOT,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:18

t2 = cos(phi);
t3 = sin(phi);
t4 = phi+q4;
t5 = phidot+q4dot;
t6 = cos(t4);
t7 = sin(t4);
Jstdot_lfoot = reshape([0.0,0.0,0.0,0.0,-l4.*phidot.*t7-(lt.*phidot.*t3)./2.0-l4.*q4dot.*t7+(phidot.*t2.*wt)./2.0,l4.*phidot.*t6+(lt.*phidot.*t2)./2.0+l4.*q4dot.*t6+(phidot.*t3.*wt)./2.0,0.0,0.0,0.0,0.0,0.0,0.0,-l4.*t5.*t7,l4.*t5.*t6],[2,7]);
end
