function B = auto_B
%auto_B
%    B = auto_B

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:18

B = reshape([0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[7,4]);
end
