function Jhdotdq = auto_Jhdotdq
%auto_Jhdotdq
%    Jhdotdq = auto_Jhdotdq

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:19

Jhdotdq = [0.0;0.0;0.0;0.0];
end
