function G = auto_G(d1,d2,d3,d4,dtx,dty,g,lt,m1,m2,m3,m4,mt,phi,q1,q2,q3,q4,wt)
%auto_G
%    G = auto_G(D1,D2,D3,D4,DTX,DTY,g,LT,M1,M2,M3,M4,MT,PHI,Q1,Q2,Q3,Q4,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:17

t2 = cos(phi);
t3 = sin(phi);
t4 = phi+q1;
t5 = phi+q2;
t6 = phi+q3;
t7 = phi+q4;
t8 = sin(t4);
t9 = sin(t5);
t10 = sin(t6);
t11 = sin(t7);
t12 = (t2.*wt)./2.0;
t13 = (lt.*t3)./2.0;
t14 = -t12;
G = [0.0;g.*(m1+m2+m3+m4+mt);g.*mt.*(dtx.*t2-dty.*t3)-g.*m1.*(t13+t14+d1.*t8)-g.*m2.*(t12+t13+d2.*t9)+g.*m3.*(t12+t13+d3.*t10)+g.*m4.*(t13+t14+d4.*t11);-d1.*g.*m1.*t8;-d2.*g.*m2.*t9;d3.*g.*m3.*t10;d4.*g.*m4.*t11];
end
