function JpCOM = auto_JpCOM(d1,d2,d3,d4,dtx,dty,lt,m1,m2,m3,m4,mt,phi,q1,q2,q3,q4,wt)
%auto_JpCOM
%    JpCOM = auto_JpCOM(D1,D2,D3,D4,DTX,DTY,LT,M1,M2,M3,M4,MT,PHI,Q1,Q2,Q3,Q4,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:19

t2 = cos(phi);
t3 = cos(q1);
t4 = cos(q2);
t5 = cos(q3);
t6 = cos(q4);
t7 = sin(phi);
t8 = sin(q1);
t9 = sin(q2);
t10 = sin(q3);
t11 = sin(q4);
t12 = phi+q1;
t13 = phi+q2;
t14 = phi+q3;
t15 = phi+q4;
t24 = lt./2.0;
t25 = wt./2.0;
t26 = m1+m2+m3+m4+mt;
t16 = d1.*t3;
t17 = d2.*t4;
t18 = d3.*t5;
t19 = d4.*t6;
t20 = d1.*t8;
t21 = d2.*t9;
t22 = d3.*t10;
t23 = d4.*t11;
t29 = 1.0./t26;
t30 = t16+t24;
t31 = t17+t24;
t32 = t18+t24;
t33 = t19+t24;
t34 = t21+t25;
t35 = t22+t25;
JpCOM = reshape([1.0,0.0,0.0,1.0,-t29.*(mt.*(dtx.*t7+dty.*t2)+m2.*(t2.*t31-t7.*t34)-m3.*(t2.*t32-t7.*t35)+m1.*(t2.*t30-t7.*(t20-t25))-m4.*(t2.*t33-t7.*(t23-t25))),t29.*(mt.*(dtx.*t2-dty.*t7)-m2.*(t2.*t34+t7.*t31)+m3.*(t2.*t35+t7.*t32)-m1.*(t7.*t30+t2.*(t20-t25))+m4.*(t7.*t33+t2.*(t23-t25))),-d1.*m1.*t29.*cos(t12),-d1.*m1.*t29.*sin(t12),-d2.*m2.*t29.*cos(t13),-d2.*m2.*t29.*sin(t13),d3.*m3.*t29.*cos(t14),d3.*m3.*t29.*sin(t14),d4.*m4.*t29.*cos(t15),d4.*m4.*t29.*sin(t15)],[2,7]);
end
