function Jst_rfoot = auto_Jst_rfoot(l3,lt,phi,q3,wt)
%auto_Jst_rfoot
%    Jst_rfoot = auto_Jst_rfoot(L3,LT,PHI,Q3,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:18

t2 = cos(phi);
t3 = cos(q3);
t4 = sin(phi);
t5 = sin(q3);
t8 = lt./2.0;
t9 = wt./2.0;
t6 = l3.*t3;
t7 = l3.*t5;
t10 = t6+t8;
t11 = t7+t9;
Jst_rfoot = reshape([1.0,0.0,0.0,1.0,t2.*t10-t4.*t11,t2.*t11+t4.*t10,0.0,0.0,0.0,0.0,t2.*t6-t4.*t7,t2.*t7+t4.*t6,0.0,0.0],[2,7]);
end
