function C = auto_C(d1,d2,d3,d4,dtx,dty,lt,m1,m2,m3,m4,mt,phi,phidot,q1,q2,q3,q4,q1dot,q2dot,q3dot,q4dot,wt)
%auto_C
%    C = auto_C(D1,D2,D3,D4,DTX,DTY,LT,M1,M2,M3,M4,MT,PHI,PHIDOT,Q1,Q2,Q3,Q4,Q1DOT,Q2DOT,Q3DOT,Q4DOT,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:17

t2 = cos(phi);
t3 = cos(q1);
t4 = cos(q2);
t5 = cos(q3);
t6 = cos(q4);
t7 = sin(phi);
t8 = sin(q1);
t9 = sin(q2);
t10 = sin(q3);
t11 = sin(q4);
t12 = phi+q1;
t13 = phi+q2;
t14 = phi+q3;
t15 = phi+q4;
t16 = phidot+q1dot;
t17 = phidot+q2dot;
t18 = phidot+q3dot;
t19 = phidot+q4dot;
t20 = cos(t12);
t21 = cos(t13);
t22 = cos(t14);
t23 = cos(t15);
t24 = t3.*wt;
t25 = t4.*wt;
t26 = t5.*wt;
t27 = t6.*wt;
t28 = lt.*t8;
t29 = lt.*t9;
t30 = lt.*t10;
t31 = lt.*t11;
t32 = sin(t12);
t33 = sin(t13);
t34 = sin(t14);
t35 = sin(t15);
t36 = -t29;
t37 = -t30;
t38 = t24+t28;
t39 = t27+t31;
t40 = t25+t36;
t41 = t26+t37;
mt1 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,d1.*m1.*phidot.*t32+d2.*m2.*phidot.*t33-d3.*m3.*phidot.*t34-d4.*m4.*phidot.*t35+d1.*m1.*q1dot.*t32+d2.*m2.*q2dot.*t33-d3.*m3.*q3dot.*t34-d4.*m4.*q4dot.*t35-dtx.*mt.*phidot.*t2+dty.*mt.*phidot.*t7+(lt.*m1.*phidot.*t7)./2.0+(lt.*m2.*phidot.*t7)./2.0-(lt.*m3.*phidot.*t7)./2.0-(lt.*m4.*phidot.*t7)./2.0-(m1.*phidot.*t2.*wt)./2.0+(m2.*phidot.*t2.*wt)./2.0-(m3.*phidot.*t2.*wt)./2.0+(m4.*phidot.*t2.*wt)./2.0];
mt2 = [-d1.*m1.*phidot.*t20-d2.*m2.*phidot.*t21+d3.*m3.*phidot.*t22+d4.*m4.*phidot.*t23-d1.*m1.*q1dot.*t20-d2.*m2.*q2dot.*t21+d3.*m3.*q3dot.*t22+d4.*m4.*q4dot.*t23-dtx.*mt.*phidot.*t7-dty.*mt.*phidot.*t2-(lt.*m1.*phidot.*t2)./2.0-(lt.*m2.*phidot.*t2)./2.0+(lt.*m3.*phidot.*t2)./2.0+(lt.*m4.*phidot.*t2)./2.0-(m1.*phidot.*t7.*wt)./2.0+(m2.*phidot.*t7.*wt)./2.0-(m3.*phidot.*t7.*wt)./2.0+(m4.*phidot.*t7.*wt)./2.0];
mt3 = [-q1dot.*((d1.*m1.*t24)./2.0+(d1.*m1.*t28)./2.0)+q2dot.*((d2.*m2.*t25)./2.0-(d2.*m2.*t29)./2.0)+q3dot.*((d3.*m3.*t26)./2.0-(d3.*m3.*t30)./2.0)-q4dot.*((d4.*m4.*t27)./2.0+(d4.*m4.*t31)./2.0),(d1.*m1.*phidot.*t38)./2.0,d2.*m2.*phidot.*t40.*(-1.0./2.0),d3.*m3.*phidot.*t41.*(-1.0./2.0),(d4.*m4.*phidot.*t39)./2.0,d1.*m1.*t16.*t32,-d1.*m1.*t16.*t20,d1.*m1.*t16.*t38.*(-1.0./2.0),0.0,0.0,0.0,0.0,d2.*m2.*t17.*t33,-d2.*m2.*t17.*t21,(d2.*m2.*t17.*t40)./2.0,0.0,0.0,0.0,0.0,-d3.*m3.*t18.*t34,d3.*m3.*t18.*t22,(d3.*m3.*t18.*t41)./2.0,0.0,0.0,0.0,0.0,-d4.*m4.*t19.*t35,d4.*m4.*t19.*t23];
mt4 = [d4.*m4.*t19.*t39.*(-1.0./2.0),0.0,0.0,0.0,0.0];
C = reshape([mt1,mt2,mt3,mt4],7,7);
end
