function p_lhand = auto_plhand(l2,lt,phi,q2,wt,x,y)
%AUTO_PLHAND
%    P_LHAND = AUTO_PLHAND(L2,LT,PHI,Q2,WT,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:16

t2 = cos(phi);
t3 = cos(q2);
t4 = sin(phi);
t5 = sin(q2);
t8 = lt./2.0;
t9 = wt./2.0;
t6 = l2.*t3;
t7 = l2.*t5;
t10 = t6+t8;
t11 = t7+t9;
p_lhand = [x-t2.*t11-t4.*t10;y+t2.*t10-t4.*t11];
end
