function Jstdot_rhand = auto_Jstdot_rhand(l1,lt,phi,phidot,q1,q1dot,wt)
%auto_Jstdot_rhand
%    Jstdot_rhand = auto_Jstdot_rhand(L1,LT,PHI,PHIDOT,Q1,Q1DOT,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:18

t2 = cos(phi);
t3 = sin(phi);
t4 = phi+q1;
t5 = phidot+q1dot;
t6 = cos(t4);
t7 = sin(t4);
Jstdot_rhand = reshape([0.0,0.0,0.0,0.0,l1.*phidot.*t7+(lt.*phidot.*t3)./2.0+l1.*q1dot.*t7-(phidot.*t2.*wt)./2.0,-l1.*phidot.*t6-(lt.*phidot.*t2)./2.0-l1.*q1dot.*t6-(phidot.*t3.*wt)./2.0,l1.*t5.*t7,-l1.*t5.*t6,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
end
