function dJpCOM = auto_dJpCOM(d1,d2,d3,d4,dtx,dty,lt,m1,m2,m3,m4,mt,phi,phidot,q1,q2,q3,q4,q1dot,q2dot,q3dot,q4dot,wt)
%auto_dJpCOM
%    dJpCOM = auto_dJpCOM(D1,D2,D3,D4,DTX,DTY,LT,M1,M2,M3,M4,MT,PHI,PHIDOT,Q1,Q2,Q3,Q4,Q1DOT,Q2DOT,Q3DOT,Q4DOT,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:19

t2 = cos(phi);
t3 = sin(phi);
t4 = phi+q1;
t5 = phi+q2;
t6 = phi+q3;
t7 = phi+q4;
t8 = phidot+q1dot;
t9 = phidot+q2dot;
t10 = phidot+q3dot;
t11 = phidot+q4dot;
t20 = m1+m2+m3+m4+mt;
t12 = cos(t4);
t13 = cos(t5);
t14 = cos(t6);
t15 = cos(t7);
t16 = sin(t4);
t17 = sin(t5);
t18 = sin(t6);
t19 = sin(t7);
t21 = 1.0./t20;
mt1 = [0.0,0.0,0.0,0.0,(t21.*(d1.*m1.*phidot.*t16.*2.0+d2.*m2.*phidot.*t17.*2.0-d3.*m3.*phidot.*t18.*2.0-d4.*m4.*phidot.*t19.*2.0+d1.*m1.*q1dot.*t16.*2.0+d2.*m2.*q2dot.*t17.*2.0-d3.*m3.*q3dot.*t18.*2.0-d4.*m4.*q4dot.*t19.*2.0-dtx.*mt.*phidot.*t2.*2.0+dty.*mt.*phidot.*t3.*2.0+lt.*m1.*phidot.*t3+lt.*m2.*phidot.*t3-lt.*m3.*phidot.*t3-lt.*m4.*phidot.*t3-m1.*phidot.*t2.*wt+m2.*phidot.*t2.*wt-m3.*phidot.*t2.*wt+m4.*phidot.*t2.*wt))./2.0];
mt2 = [t21.*(d1.*m1.*phidot.*t12.*2.0+d2.*m2.*phidot.*t13.*2.0-d3.*m3.*phidot.*t14.*2.0-d4.*m4.*phidot.*t15.*2.0+d1.*m1.*q1dot.*t12.*2.0+d2.*m2.*q2dot.*t13.*2.0-d3.*m3.*q3dot.*t14.*2.0-d4.*m4.*q4dot.*t15.*2.0+dtx.*mt.*phidot.*t3.*2.0+dty.*mt.*phidot.*t2.*2.0+lt.*m1.*phidot.*t2+lt.*m2.*phidot.*t2-lt.*m3.*phidot.*t2-lt.*m4.*phidot.*t2+m1.*phidot.*t3.*wt-m2.*phidot.*t3.*wt+m3.*phidot.*t3.*wt-m4.*phidot.*t3.*wt).*(-1.0./2.0),d1.*m1.*t8.*t16.*t21,-d1.*m1.*t8.*t12.*t21,d2.*m2.*t9.*t17.*t21,-d2.*m2.*t9.*t13.*t21,-d3.*m3.*t10.*t18.*t21,d3.*m3.*t10.*t14.*t21,-d4.*m4.*t11.*t19.*t21,d4.*m4.*t11.*t15.*t21];
dJpCOM = reshape([mt1,mt2],2,7);
end
