function Jstdot_lhand = auto_Jstdot_lhand(l2,lt,phi,phidot,q2,q2dot,wt)
%auto_Jstdot_lhand
%    Jstdot_lhand = auto_Jstdot_lhand(L2,LT,PHI,PHIDOT,Q2,Q2DOT,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:18

t2 = cos(phi);
t3 = sin(phi);
t4 = phi+q2;
t5 = phidot+q2dot;
t6 = cos(t4);
t7 = sin(t4);
Jstdot_lhand = reshape([0.0,0.0,0.0,0.0,l2.*phidot.*t7+(lt.*phidot.*t3)./2.0+l2.*q2dot.*t7+(phidot.*t2.*wt)./2.0,-l2.*phidot.*t6-(lt.*phidot.*t2)./2.0-l2.*q2dot.*t6+(phidot.*t3.*wt)./2.0,0.0,0.0,l2.*t5.*t7,-l2.*t5.*t6,0.0,0.0,0.0,0.0],[2,7]);
end
