function p_lfoot = auto_plfoot(l4,lt,phi,q4,wt,x,y)
%AUTO_PLFOOT
%    P_LFOOT = AUTO_PLFOOT(L4,LT,PHI,Q4,WT,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:16

t2 = cos(phi);
t3 = cos(q4);
t4 = sin(phi);
t5 = sin(q4);
t8 = lt./2.0;
t9 = wt./2.0;
t6 = l4.*t3;
t7 = l4.*t5;
t11 = t6+t8;
p_lfoot = [x+t4.*t11+t2.*(t7-t9);y-t2.*t11+t4.*(t7-t9)];
end
