function Jhdot = auto_Jhdot
%auto_Jhdot
%    Jhdot = auto_Jhdot

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:19

Jhdot = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,7]);
end
