function p_rfoot = auto_prfoot(l3,lt,phi,q3,wt,x,y)
%AUTO_PRFOOT
%    P_RFOOT = AUTO_PRFOOT(L3,LT,PHI,Q3,WT,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:16

t2 = cos(phi);
t3 = cos(q3);
t4 = sin(phi);
t5 = sin(q3);
t8 = lt./2.0;
t9 = wt./2.0;
t6 = l3.*t3;
t7 = l3.*t5;
t10 = t6+t8;
t11 = t7+t9;
p_rfoot = [x+t2.*t11+t4.*t10;y-t2.*t10+t4.*t11];
end
