function Jst_rhand = auto_Jst_rhand(l1,lt,phi,q1,wt)
%auto_Jst_rhand
%    Jst_rhand = auto_Jst_rhand(L1,LT,PHI,Q1,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:18

t2 = cos(phi);
t3 = cos(q1);
t4 = sin(phi);
t5 = sin(q1);
t8 = lt./2.0;
t9 = wt./2.0;
t6 = l1.*t3;
t7 = l1.*t5;
t10 = -t7;
t11 = t6+t8;
Jst_rhand = reshape([1.0,0.0,0.0,1.0,-t2.*t11+t4.*(t7-t9),-t4.*t11-t2.*(t7-t9),-t2.*t6+t4.*t7,-t4.*t6+t2.*t10,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
end
