function Jstdot_rfoot = auto_Jstdot_rfoot(l3,lt,phi,phidot,q3,q3dot,wt)
%auto_Jstdot_rfoot
%    Jstdot_rfoot = auto_Jstdot_rfoot(L3,LT,PHI,PHIDOT,Q3,Q3DOT,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:18

t2 = cos(phi);
t3 = sin(phi);
t4 = phi+q3;
t5 = phidot+q3dot;
t6 = cos(t4);
t7 = sin(t4);
Jstdot_rfoot = reshape([0.0,0.0,0.0,0.0,-l3.*phidot.*t7-(lt.*phidot.*t3)./2.0-l3.*q3dot.*t7-(phidot.*t2.*wt)./2.0,l3.*phidot.*t6+(lt.*phidot.*t2)./2.0+l3.*q3dot.*t6-(phidot.*t3.*wt)./2.0,0.0,0.0,0.0,0.0,-l3.*t5.*t7,l3.*t5.*t6,0.0,0.0],[2,7]);
end
