function Jst_lfoot = auto_Jst_lfoot(l4,lt,phi,q4,wt)
%auto_Jst_lfoot
%    Jst_lfoot = auto_Jst_lfoot(L4,LT,PHI,Q4,WT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:18

t2 = cos(phi);
t3 = cos(q4);
t4 = sin(phi);
t5 = sin(q4);
t8 = lt./2.0;
t9 = wt./2.0;
t6 = l4.*t3;
t7 = l4.*t5;
t10 = -t7;
t11 = t6+t8;
Jst_lfoot = reshape([1.0,0.0,0.0,1.0,t2.*t11-t4.*(t7-t9),t4.*t11+t2.*(t7-t9),0.0,0.0,0.0,0.0,0.0,0.0,t2.*t6+t4.*t10,t2.*t7+t4.*t6],[2,7]);
end
