function Lfh = auto_Lfh(q1dot,q2dot,q3dot,q4dot)
%auto_Lfh
%    Lfh = auto_Lfh(Q1DOT,Q2DOT,Q3DOT,Q4DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Nov-2025 14:59:19

Lfh = [q1dot;q2dot;q3dot;q4dot];
end
