function Lfy = Lfy_auto(in1,in2,in3,in4,in5,th1_des)
%Lfy_auto
%    Lfy = Lfy_auto(IN1,IN2,IN3,IN4,IN5,TH1_DES)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Dec-2025 18:40:49

a1 = in2(2,:);
a2 = in2(3,:);
a3 = in2(4,:);
b1 = in3(2,:);
b2 = in3(3,:);
b3 = in3(4,:);
c1 = in4(2,:);
c2 = in4(3,:);
c3 = in4(4,:);
d0 = in5(1,:);
d1 = in5(2,:);
d2 = in5(3,:);
d3 = in5(4,:);
q1 = in1(3,:);
q5 = in1(7,:);
q1dot = in1(10,:);
q2dot = in1(11,:);
q3dot = in1(12,:);
q4dot = in1(13,:);
q5dot = in1(14,:);
t2 = pi.*2.0;
t3 = q1.*2.0;
t4 = q5.*2.0;
t5 = -pi;
t7 = -th1_des;
t6 = -t2;
t8 = q1+q5+t5;
t9 = t8+th1_des;
t10 = t8.^2;
t11 = t8.^3;
t12 = d1.*t8;
t15 = t3+t4+t6;
t16 = t7+t8;
t13 = d2.*t10;
t14 = d3.*t11;
t17 = a3.*t10.*3.0;
t18 = b3.*t10.*3.0;
t19 = c3.*t10.*3.0;
t20 = d3.*t10.*3.0;
t21 = a2.*t15;
t22 = b2.*t15;
t23 = c2.*t15;
t24 = d2.*t15;
t25 = d1+t20+t24;
t26 = d0+t12+t13+t14;
t27 = t9.*t26;
t28 = t16.*t26;
t29 = t9.*t16.*t25;
Lfy = [-q1dot.*(a1+t17+t21)-q5dot.*(a1+t17+t21-1.0);q4dot-q1dot.*(b1+t18+t22)-q5dot.*(b1+t18+t22-1.0);q3dot-q1dot.*(c1+t19+t23)-q5dot.*(c1+t19+t23-1.0);q2dot-q1dot.*(t27+t28+t29-1.0)-q5dot.*(t27+t28+t29-2.0)];
end
