function p_A4 = p_A4_auto(in1)
%p_A4_auto
%    p_A4 = p_A4_auto(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Dec-2025 18:40:17

q4 = in1(6,:);
q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q4+q5;
p_A4 = [x+sin(q5)./2.0+sin(t2).*(3.0./4.0);y+cos(q5)./2.0+cos(t2).*(3.0./4.0)];
end
