function p_L1 = p_L1_auto(in1)
%p_L1_auto
%    p_L1 = p_L1_auto(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Dec-2025 18:40:16

q1 = in1(3,:);
q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q1+q5;
p_L1 = [x+sin(t2);y+cos(t2)];
end
