function p_com_A3 = p_com_A3_auto(in1)
%p_com_A3_auto
%    p_com_A3 = p_com_A3_auto(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Dec-2025 12:29:18

q3 = in1(5,:);
q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q3+q5;
p_com_A3 = [x+sin(q5)./2.0+sin(t2).*(3.0./8.0);y+cos(q5)./2.0+cos(t2).*(3.0./8.0)];
end
