function p_L2 = p_L2_auto(in1)
%p_L2_auto
%    p_L2 = p_L2_auto(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Dec-2025 12:29:18

q2 = in1(4,:);
q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q2+q5;
p_L2 = [x+sin(t2);y+cos(t2)];
end
