function p_sw = p_sw_auto(in1)
%P_SW_AUTO
%    P_SW = P_SW_AUTO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Dec-2025 12:29:18

q2 = in1(4,:);
q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q2+q5;
p_sw = [x+sin(t2);y+cos(t2)];
end
