function y = y_auto(in1,in2,in3,in4,in5,th1_des)
%Y_AUTO
%    Y = Y_AUTO(IN1,IN2,IN3,IN4,IN5,TH1_DES)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Dec-2025 12:29:48

a0 = in2(1,:);
a1 = in2(2,:);
a2 = in2(3,:);
a3 = in2(4,:);
b0 = in3(1,:);
b1 = in3(2,:);
b2 = in3(3,:);
b3 = in3(4,:);
c0 = in4(1,:);
c1 = in4(2,:);
c2 = in4(3,:);
c3 = in4(4,:);
d0 = in5(1,:);
d1 = in5(2,:);
d2 = in5(3,:);
d3 = in5(4,:);
q1 = in1(3,:);
q2 = in1(4,:);
q3 = in1(5,:);
q4 = in1(6,:);
q5 = in1(7,:);
t2 = -pi;
t3 = q1+q5+t2;
t4 = t3.^2;
t5 = t3.^3;
y = [-a0+q5-a1.*t3-a2.*t4-a3.*t5;-b0+q4+q5+t2-b1.*t3-b2.*t4-b3.*t5;-c0+q3+q5+t2-c1.*t3-c2.*t4-c3.*t5;q1+q2+q5.*2.0-pi.*2.0-(t3+th1_des).*(t3-th1_des).*(d0+d1.*t3+d2.*t4+d3.*t5)];
end
