function Lfy_hp = Lfy_hp_auto(in1,in2)
%Lfy_hp_auto
%    Lfy_hp = Lfy_hp_auto(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:28:31

q1dot = in1(10,:);
q2dot = in1(11,:);
q3dot = in1(12,:);
q4dot = in1(13,:);
q5dot = in1(14,:);
Lfy_hp = [q5dot;q4dot+q5dot;q3dot+q5dot;-q1dot+q2dot];
end
