function Lfy_st = Lfy_st_auto(in1,in2)
%Lfy_st_auto
%    Lfy_st = Lfy_st_auto(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:26:02

q1dot = in1(10,:);
q2dot = in1(11,:);
q3dot = in1(12,:);
q4dot = in1(13,:);
q5dot = in1(14,:);
Lfy_st = [q5dot;q4dot+q5dot;q3dot+q5dot;q1dot+q2dot+q5dot.*2.0];
end
