function p_com_T = p_com_T_auto(in1)
%p_com_T_auto
%    p_com_T = p_com_T_auto(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:18:34

q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
p_com_T = [x+sin(q5)./2.0;y+cos(q5)./2.0];
end
