function p_com_L1 = p_com_L1_auto(in1)
%p_com_L1_auto
%    p_com_L1 = p_com_L1_auto(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:18:34

q1 = in1(3,:);
q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q1+q5;
p_com_L1 = [x+sin(t2)./2.0;y+cos(t2)./2.0];
end
