function p_H = p_H_auto(in1)
%p_H_auto
%    p_H = p_H_auto(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:18:35

x = in1(1,:);
y = in1(2,:);
p_H = [x;y];
end
