function p_hp = p_hp_auto(in1)
%P_HP_AUTO
%    P_HP = P_HP_AUTO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:28:07

q3 = in1(5,:);
q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q3+q5;
p_hp = [x+sin(q5)+sin(t2).*(3.0./4.0);y+cos(q5)+cos(t2).*(3.0./4.0)];
end
