function p_S = p_S_auto(in1)
%p_S_auto
%    p_S = p_S_auto(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:18:35

q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
p_S = [x+sin(q5);y+cos(q5)];
end
