function p_st = p_st_auto(in1)
%P_ST_AUTO
%    P_ST = P_ST_AUTO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:19:57

q1 = in1(3,:);
q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q1+q5;
p_st = [x+sin(t2);y+cos(t2)];
end
