function p_su_i = p_su_i_auto(in1)
%P_SU_I_AUTO
%    P_SU_I = P_SU_I_AUTO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:52:44

q4 = in1(6,:);
q5 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q4+q5;
p_su_i = [x+sin(q5)+sin(t2).*(3.0./4.0);y+cos(q5)+cos(t2).*(3.0./4.0)];
end
