function y_st = y_st_auto(in1,in2)
%Y_ST_AUTO
%    Y_ST = Y_ST_AUTO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 12:26:02

q1 = in1(3,:);
q2 = in1(4,:);
q3 = in1(5,:);
q4 = in1(6,:);
q5 = in1(7,:);
th3_des = in2(3,:);
th4_des = in2(4,:);
th5_des = in2(5,:);
t2 = -pi;
y_st = [q5-th5_des;q4+q5+t2-th4_des;q3+q5+t2-th3_des;q1+q2+q5.*2.0-pi.*2.0];
end
