function y_su = y_su_auto(in1,in2)
%Y_SU_AUTO
%    Y_SU = Y_SU_AUTO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Dec-2025 14:11:57

q1 = in1(3,:);
q2 = in1(4,:);
q3 = in1(5,:);
q4 = in1(6,:);
q5 = in1(7,:);
th1_des = in2(1,:);
th2_des = in2(2,:);
th5_des = in2(5,:);
t2 = -pi;
y_su = [q5-th5_des;q3+q4+q5.*2.0-pi.*2.0;q2+q5+t2-th2_des;q1+q5+t2-th1_des];
end
